---------- Calculate the average rating and total revenue for each hotel, and order by descending total revenue:
WITH hotel_avg_rating AS (
  SELECT
    hotel_id,
    AVG(rating_score) AS avg_rating
  FROM
    hotel_reviews
  GROUP BY
    hotel_id
),
hotel_revenue AS (
  SELECT
    hotels.hotel_id,
    SUM(hotel_reservations.prices) AS total_revenue
  FROM
    hotels
    JOIN rooms ON hotels.hotel_id = rooms.hotel_id
    JOIN hotel_reservations ON rooms.room_id = hotel_reservations.room_id
  GROUP BY
    hotels.hotel_id
),
hotel_rating_revenue AS (
  SELECT
    hotel_avg_rating.hotel_id,
    hotels.name,
    avg_rating,
    COALESCE(total_revenue, 0) AS total_revenue
  FROM
    hotel_avg_rating
    JOIN hotels ON hotel_avg_rating.hotel_id = hotels.hotel_id
    LEFT JOIN hotel_revenue ON hotel_avg_rating.hotel_id = hotel_revenue.hotel_id
)
SELECT
  hotel_id,
  name,
  avg_rating,
  total_revenue
FROM
  hotel_rating_revenue
ORDER BY
  total_revenue DESC;
----------


---------- Calculates the average rental review ratings for each car manufacturer and model
WITH rental_reviews_stats AS (
  SELECT
    cars.manufacturer,
    cars.model,
    AVG(rental_reviews.rating_score) AS avg_rating
  FROM
    rental_reviews
    JOIN cars ON rental_reviews.car_id = cars.car_id
  GROUP BY
    cars.manufacturer,
    cars.model
),
rental_stats AS (
  SELECT
    cars.manufacturer,
    cars.model,
    COUNT(rent_reservations.id) AS total_rentals
  FROM
    rent_reservations
    JOIN cars ON rent_reservations.car_id = cars.car_id
  GROUP BY
    cars.manufacturer,
    cars.model
),
combined_stats AS (
  SELECT
    COALESCE(r.manufacturer, s.manufacturer) AS manufacturer,
    COALESCE(r.model, s.model) AS model,
    r.avg_rating,
    s.total_rentals
  FROM
    rental_reviews_stats r
    FULL OUTER JOIN rental_stats s ON (r.manufacturer = s.manufacturer) AND (r.model = s.model)
)
SELECT
  manufacturer,
  model,
  COALESCE(avg_rating, 0) AS avg_rating
FROM
  combined_stats
ORDER BY
  avg_rating DESC, total_rentals DESC;
----------

---------- Distribution of ticket classes purchased by guests based on their loyalty group
SELECT
  user_loyalty.loyalty_group,
  ticket_prices.classes,
  COUNT(ticket_prices.ticket_id) AS total_tickets,
  COUNT(ticket_prices.ticket_id)::FLOAT / SUM(COUNT(ticket_prices.ticket_id)) OVER (PARTITION BY user_loyalty.loyalty_group) * 100 AS percentage
FROM
  ticket_prices
  JOIN flights ON ticket_prices.flight_id = flights.flight_id
  JOIN guests ON flights.passenger_id = guests.guest_id
  JOIN user_loyalty ON guests.guest_id = user_loyalty.guest_id
GROUP BY
  user_loyalty.loyalty_group,
  ticket_prices.classes
ORDER BY
  user_loyalty.loyalty_group,
  ticket_prices.classes;
----------


---------- Calculate the total revenue and total loyalty points earned for each user.
CREATE OR REPLACE FUNCTION user_revenue_and_loyalty()
RETURNS TABLE (
  guest_id INT,
  guest_name VARCHAR,
  total_revenue DECIMAL,
  total_loyalty_points DECIMAL
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    g.guest_id,
    (g.first_name || ' ' || g.last_name)::VARCHAR as guest_name,
    SUM(hr.prices) + SUM(tp.prices) + SUM(rr.prices) as total_revenue,
    SUM(ul.activity) as total_loyalty_points
  FROM
    guests g
  LEFT JOIN hotel_reservations hr ON g.guest_id = hr.guest_id
  LEFT JOIN ticket_prices tp ON g.guest_id = tp.reservation_id
  LEFT JOIN rent_reservations rr ON g.guest_id = rr.guest_id
  LEFT JOIN user_loyalty ul ON g.guest_id = ul.guest_id
  GROUP BY
    g.guest_id,
    guest_name
  ORDER BY
    total_revenue DESC;
END;
$$ LANGUAGE plpgsql;
-------------

SELECT * FROM user_revenue_and_loyalty();



------------- Calculate the total revenue generated by each loyalty group:
WITH guest_revenue AS (
  SELECT
    guest_id,
    SUM(prices) AS total_revenue
  FROM
    hotel_reservations
  GROUP BY
    guest_id
),
loyalty_group_revenue AS (
  SELECT
    user_loyalty.loyalty_group,
    SUM(guest_revenue.total_revenue) AS total_revenue
  FROM
    user_loyalty
    JOIN guest_revenue ON user_loyalty.guest_id = guest_revenue.guest_id
  GROUP BY
    user_loyalty.loyalty_group
)
SELECT
  loyalty_group,
  total_revenue
FROM
  loyalty_group_revenue
ORDER BY
  total_revenue DESC;
-------------



------------- Cohort analysis: Calculate the retention rate of guests based on their first reservation month
WITH cohort AS (
  SELECT
    guest_id,
    DATE_TRUNC('month', MIN(date)) AS cohort_month
  FROM
    hotel_reservations
  GROUP BY
    guest_id
),
monthly_activity AS (
  SELECT
    cohort.guest_id,
    DATE_TRUNC('month', hotel_reservations.date) AS activity_month
  FROM
    cohort
    JOIN hotel_reservations ON cohort.guest_id = hotel_reservations.guest_id
),
cohort_size AS (
  SELECT
    cohort_month,
    COUNT(DISTINCT guest_id) AS cohort_size
  FROM
    cohort
  GROUP BY
    cohort_month
),
activity_by_cohort AS (
  SELECT
    cohort.cohort_month,
    monthly_activity.activity_month,
    COUNT(DISTINCT cohort.guest_id) AS active_guests
  FROM
    cohort
    JOIN monthly_activity ON cohort.guest_id = monthly_activity.guest_id
  GROUP BY
    cohort.cohort_month,
    monthly_activity.activity_month
),
retention_rate AS (
  SELECT
    activity_by_cohort.cohort_month,
    activity_by_cohort.activity_month,
    active_guests::FLOAT / cohort_size::FLOAT * 100 AS retention_rate
  FROM
    activity_by_cohort
    JOIN cohort_size ON activity_by_cohort.cohort_month = cohort_size.cohort_month
)
SELECT
  cohort_month,
  activity_month,
  retention_rate
FROM
  retention_rate
ORDER BY
  cohort_month,
  activity_month;
----------



---------- RFM analysis: Calculate Recency, Frequency, and Monetary value for each guest
WITH guest_activity AS (
  SELECT
    guest_id,
    MAX(date) AS last_reservation_date,
    COUNT(*) AS total_reservations,
    SUM(prices) AS total_revenue
  FROM
    hotel_reservations
  GROUP BY
    guest_id
),
rfm AS (
  SELECT
    guest_id,
    EXTRACT(EPOCH FROM (NOW() - last_reservation_date)) / 86400 AS recency,
    total_reservations AS frequency,
    total_revenue AS monetary
  FROM
    guest_activity
)
SELECT
  guest_id,
  recency,
  frequency,
  monetary
FROM
  rfm
ORDER BY
  guest_id;
----------


---------- Compare the percentage of guests participated in 1, 2, 3 activities
WITH guest_activity_count AS (
  SELECT
    guests.guest_id,
    COUNT(DISTINCT hotel_reservations.id) AS hotel_count,
    COUNT(DISTINCT rent_reservations.id) AS rent_count,
    COUNT(DISTINCT flights.flight_id) AS flight_count
  FROM
    guests
    LEFT JOIN hotel_reservations ON guests.guest_id = hotel_reservations.guest_id
    LEFT JOIN rent_reservations ON guests.guest_id = rent_reservations.guest_id
    LEFT JOIN flights ON guests.guest_id = flights.passenger_id
  GROUP BY
    guests.guest_id
),
activity_stats AS (
  SELECT
    SUM(CASE WHEN hotel_count > 0 AND rent_count = 0 AND flight_count = 0 THEN 1 ELSE 0 END)::FLOAT / COUNT(*)::FLOAT * 100 AS hotel_only_percentage,
    SUM(CASE WHEN hotel_count = 0 AND rent_count > 0 AND flight_count = 0 THEN 1 ELSE 0 END)::FLOAT / COUNT(*)::FLOAT * 100 AS rent_only_percentage,
    SUM(CASE WHEN hotel_count = 0 AND rent_count = 0 AND flight_count > 0 THEN 1 ELSE 0 END)::FLOAT / COUNT(*)::FLOAT * 100 AS flight_only_percentage,
    SUM(CASE WHEN hotel_count > 0 AND rent_count > 0 AND flight_count = 0 THEN 1 ELSE 0 END)::FLOAT / COUNT(*)::FLOAT * 100 AS hotel_rent_percentage,
    SUM(CASE WHEN hotel_count > 0 AND rent_count = 0 AND flight_count > 0 THEN 1 ELSE 0 END)::FLOAT / COUNT(*)::FLOAT * 100 AS hotel_flight_percentage,
    SUM(CASE WHEN hotel_count = 0 AND rent_count > 0 AND flight_count > 0 THEN 1 ELSE 0 END)::FLOAT / COUNT(*)::FLOAT * 100 AS rent_flight_percentage,
    SUM(CASE WHEN hotel_count > 0 AND rent_count > 0 AND flight_count > 0 THEN 1 ELSE 0 END)::FLOAT / COUNT(*)::FLOAT * 100 AS all_activities_percentage
  FROM
    guest_activity_count
)
SELECT
  hotel_only_percentage,
  rent_only_percentage,
  flight_only_percentage,
  hotel_rent_percentage,
  hotel_flight_percentage,
  rent_flight_percentage,
  all_activities_percentage
FROM
  activity_stats;
----------










